### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [dsekercioglu/blackmarlin#109]
Can you build a Korean chess engine?

**Comment by GuyClicking** [comment]
omg yes please make one using UCI korean edition

**Comment by cjssh1002** [comment]
I inquired about the traditional Korean chess engine.(game name: Janggi)
Janggi is famous in Korea along with Go. 
However, the Janggi is almost nonexistent because it is not widely known in the world.
Janggi engine can be run in Winboard GUI using UCI or CECP protocol.
Could you possibly make Korean Janggi engine?
It uses a 9x10 board.
![12](https://user-images.githubusercontent.com/63978900/167886657-41ea4dbe-cd02-4f78-95af-69fcf32cd0d5.PNG)

**Comment by dsekercioglu** [comment]
I don't have any plans to build a Janggi engine any time soon.
