### ISSUE TITLE
compiling v6.0 fails on Linux

### ISSUE THREAD

**Issue by tissatussa** [dsekercioglu/blackmarlin#122]
normally i'm able to compile rust code, but your source gives me errors :

```
$ make
EVALFILE=./nn/default.bin cargo +stable rustc --release -- -C target-cpu=native --emit link=BlackMarlin
   Compiling cozy-chess-types v0.1.4
   Compiling blackmarlin v0.1.0 (/home/roelof/Compiled/blackmarlin)
   Compiling text_io v0.1.10
   Compiling arrayvec v0.7.2
   Compiling cozy-chess v0.2.2
error: values of the type `[[i16; 544108393]; 1936876918]` are too big for the current architecture

error: could not compile `blackmarlin` due to previous error
make: *** [makefile:11: rule] Error 101
```

NOTE: your asset v3 works for me! (v4 didn't, the others i didn't try .. eg. which asset binary is avx2?)

I'm on Xubuntu 21.10

**Comment by dsekercioglu** [comment]
Black Marlin requires Git LFS to download networks. This is mentioned in the README though it can be made clearer. I might consider a custom error message for this.

x86-64-v3 requires AVX-2, v4 requires AVX-512. I will also edit release notes as micro architecture levels might not be as clear at the first look.

**Comment by tissatussa** [comment]
thanks! I managed to install Git LFS on Xubuntu by https://efrecon.github.io/git-lfs-on-ubuntu/ (also works on 21.10) and then i successfully compiled your v6.0 by its source. Indeed, it was clearly in the README ..
