### ISSUE TITLE
compile warning on Linux and versioning

### ISSUE THREAD

**Issue by tissatussa** [dsekercioglu/blackmarlin#141]
hi,

i see that you update the main code regularly .. compiling it on Linux succeeds, but i get this warning :
 
```
~/Compiled/blackmarlin$ make
EVALFILE=./nn/default.bin cargo rustc --release -- -C target-cpu=native --emit link=BlackMarlin
   Compiling cozy-chess-types v0.1.4
   Compiling blackmarlin v0.1.0 (/home/roelof/Compiled/blackmarlin)
   Compiling arrayvec v0.7.2
   Compiling text_io v0.1.10
   Compiling cozy-chess v0.2.2
warning: unused import: `crate::bm::bm_util::h_table`
 --> src/bm/bm_search/search.rs:8:5
  |
8 | use crate::bm::bm_util::h_table;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `blackmarlin` (bin "blackmarlin") generated 1 warning
    Finished release [optimized] target(s) in 25.14s
```

the compiled binary is 28.8 Mb and shows v6.0 .. all other recent versions also show v6.0 .. it seems you don't use a development version, you just update "main" .. could it be handy to sub-version your next releases ?  Eg. v6.0.1 etc.

[ i'm on Xubuntu 22.04 ]

**Comment by dsekercioglu** [comment]
The compiler warning has now been fixed.

About the versions, I don't really find versions meaningful other than for releases. The convention I follow is x.y where x is changed for each release, and y is changed if a bug fix is done on the release.
