### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by SzotsGabor** [dsekercioglu/blackmarlin#21]
Using the recommended command line (cargo build --release --features 'nnue') I get this error message:

error: none of the selected packages contains these features: 'nnue', did you mean: nnue?

I can successfully compile it with the simple cargo build --release but I am not sure the NNUE is included in the exe. Also, I get many warnings (mostly about unused variables).

**Comment by dsekercioglu** [comment]
In that case, doing just nnue and not 'nnue' should fix the issue.

About the other issue, I'll recompile the binaries and release them without the "dev" their names.

**Comment by SzotsGabor** [comment]
> In that case, doing just nnue and not 'nnue' should fix the issue.
> 
> About the other issue, I'll recompile the binaries and release them without the "dev" their names.

Yes, nnue without the quotes was accepted. Thanks on both accounts.

If I understand things correctly, the nnue.bin file is not needed to run the engine, it is embedded in the executable.

**Comment by dsekercioglu** [comment]
Yes, it is parsed at compile time and included in the binary. I'll also make sure to not include the quotes in the next versions in order to make things easier.
