### ISSUE TITLE
embedded NN with v5.0 ?

### ISSUE THREAD

**Issue by tissatussa** [dsekercioglu/blackmarlin#85]
i succesfully compiled your source on Linux .. i used git clone to get the source files and after compiling the UCI info states v5.0 ?! The file is 4.5 Mb -- what about the NN ? Normally i see NNUE files of 20 Mb ..

**Comment by dsekercioglu** [comment]
In order to ensure that the version number is right, I increment version numbers right after release.
Black Marlin NN is rather small so it doesn't take much space and it is embedded into the executable.
